# 01. Variables

Note: = in python means "binding" or "assigning" values

In [2]:
x = 10
x

10

In [3]:
X

NameError: name 'X' is not defined

In [4]:
y= 10
print(y)

10


# 02. Numbers and Boolean

In [11]:
x1=-1
x2=2.23

In [12]:
# Type function will tell you what type of function it is

type(x1)

int

In [13]:
type(x2)

float

In [14]:
# now we have 2 functions int and float, which will turn values form one form to toher

int(x2)

2

In [15]:
float(x1)

-1.0

## Boolean Values

0 or 1   
True or False   
Right or Wrong   
Yes or No   

In [16]:
# You can assign boolean values to your variables. But are case sensitive

x3 = True

In [17]:
x3

True

In [18]:
x4 = true

NameError: name 'true' is not defined

# 03. Strings

In [19]:
Biswa

NameError: name 'Biswa' is not defined

In [20]:
'Biswa'

'Biswa'

In [21]:
"Biswa"

'Biswa'

In [22]:
# with print we will be seeing without any quotes

print('Biswa')

Biswa


In [23]:
print("Biswa")

Biswa


In [24]:
x5= 'Biswa'
x5

'Biswa'

In [25]:
y = 10 
print(y + " Rupees")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [26]:
# NOTE: we cannot combine a integer and a string

y = 10 
print(str(y) + " Rupees")

10 Rupees


In [27]:
'I'm fine'

SyntaxError: invalid syntax (<ipython-input-27-4b03f9290adb>, line 1)

In [29]:
'I\'m fine'

"I'm fine"

In [30]:
"I'm fine"

"I'm fine"

In [31]:
'press "Enter"'

'press "Enter"'

In [32]:
'red' 'car'

'redcar'

In [33]:
'red ' 'car'

'red car'

In [34]:
'red ' + 'car'

'red car'

In [35]:
# print with a comma, will give a default space between 2
print('red','car')

red car


In [36]:
print(3,5)

3 5


In [37]:
3,4,5,6,'car'

(3, 4, 5, 6, 'car')

# 04. Basic Python Syntax

In [40]:
# 3 and 4 are callend Operands
# + is the operator 

3 + 4

7

In [41]:
3-5

-2

In [44]:
15 / 3

5.0

In [45]:
16 / 3
# this in python 2 we will get 5. For that we need to chage the float values to get 5.3333333

5.333333333333333

In [46]:
16.0 / 3

5.333333333333333

In [47]:
# Percentile will give the remainder
16 % 3

1

In [48]:
5 * 3

15

In [49]:
x = 5 * 3
x

15

In [50]:
5 ** 3

125

In [51]:
y = 5 ** 3
y

125

In [52]:
# double equal to operator compares the data and tell if both are equal or not. It will return, boolean value, True or False

y == 125

True

In [53]:
y == 126

False

### Reassigning

In [54]:
z = 1
z

1

In [55]:
z = 3
z

3

We can note that order will reassign the values

### Comments

In [ ]:
# Comment 1
# Comment 2

### Line Continution

In [56]:
3 * 4 + 5

17

In [57]:
3 * 4 + \
5

17

### Indexing elements

In [58]:
"Friday"[4]

'a'

## Structure your code with Indentation

tab helps for code indentaion in python

In [66]:
def five(x):
    x = 5
    return x
    print(five(3)) # this is inside code, so it wont execute

In [67]:
print(five(3))

5


# 0.5 Operators

## Comparision Operator

==  
!=  
>   
<  
<=  
>=

In [68]:
# Equal to operator
10 == 20/2

True

In [69]:
# not equal to operator
10 != 10

False

In [70]:
10 != 15

True

In [71]:
100 > 50

True

In [72]:
100 < 50

False

In [73]:
15 >= 10 + 10

False

## Logical  operator

In [75]:
True and True

True

In [76]:
True and False

False

In [77]:
True or False

True

In [78]:
False and False

False

In [79]:
not True

False

In [80]:
not False

True

In [81]:
3 > 5 and 5!=0

False

In [82]:
3 < 5 and 5!=0

True

In [83]:
True and not True

False

In [84]:
# and have more weitage than or
False and not True and True

False

In [86]:
True and not True or True

True

## Identity Operator

In [87]:
5 is 6

False

In [89]:
5 == 6

False

In [88]:
5 is not 6

True

In [90]:
5 != 6

True

# 06. Conditional Statements

if condition:
    #Condition code
elif condition:
    #Condition Code
else:
    #Condition Code

In [93]:
if 5 == 15/3:
    print("Horrayy..!!")

Horrayy..!!


In [94]:
if 5 == 18/3:
    print("Horrayy..!!")

Note: You can see it did not return anything, as the cond. is false and we did not have anything to do if code is false.

In [95]:
if 5 != 6*3:
    print("Horrayy...!!")

Horrayy...!!


In [100]:
x = 1

if x > 3:
    print("Case 1")
if x <= 3:
    print("Case 2")

Case 2


In [99]:
# same above code can be replaced by a else statement, but shoud be indented

x = 1

if x > 3:
    print("Case 1")
else: 
    print("Case 2")

Case 2


In [101]:
x = 1

if x > 3:
    print("Case 1")
    else: 
        print("Case 2")

SyntaxError: invalid syntax (<ipython-input-101-3cd44600f2e1>, line 5)

In [107]:
def comp_to_five(x):
    if x>5:
        print("Greater")
    elif x<0:
        print("Negative")
    elif x<5:
        print("Less")
    else:
        print("Equal")

In [105]:
comp_to_five(5)

Equal


In [106]:
comp_to_five(6)

Greater


In [108]:
comp_to_five(-4)

Negative


NOTE: Order of flow of commands is very important for computer to understand the code.

In [110]:
def comp_to_five_1(x):
    if x>5:
        print("Greater")
    elif x<5:
        print("Less")
    elif x<0:
        print("Negative")
    else:
        print("Equal")

In [112]:
comp_to_five_1(-3)
# Note: due to the order of sequence, output is not perfect, as we have given our logic in a wrong order

Less


# 07. Python Functions

In [115]:
# def is a keyword, it is neither a function or a operator
def simple():
    print("Hello")

# a fucntion will not do anything itself. we have to call the function to perform

In [114]:
simple()

Hello


## Creating a function with parameter

NOTE: This means a function can take multiple inputs as parameters def x(a,b,c,d): and give a single return output y

Naming function names properly is a good style of coding practices

In [117]:
def plus_ten(a):
    return a+10

In [118]:
plus_ten(3)

13

## Another way to writing a function

you can assign value to a variable and return the same.

NOTE: you can not have more than 2 returns in a function

In [119]:
def plus_ten_1(a):
    result = a + 10
    return result

In [120]:
plus_ten_1(5)

15

In [121]:
def plus_ten_1(a):
    result = a + 10
    return "Outcome"
    return result

In [123]:
plus_ten_1(5)
# we can see it will return only one in side a function

'Outcome'

In [124]:
# But we can return and print at a same time

def plus_ten_2(a):
    result = a + 10
    print( "Outcome")
    return result

In [125]:
plus_ten_2(3)

Outcome


13

## A function inside a function

Ex: you get daily 1000 rupees/ hour. If you do well in a day, you boss will give extra 4000 rupees

In [132]:
def wage(hours):
    return hours * 1000

def bonus(hours):
    return wage(hours) + 4000

def total_salary_per_month(hours):
    return wage(hours) * 30

In [128]:
wage(8), bonus(8)

(8000, 12000)

In [133]:
total_salary_per_month(8)

240000

## Combining conditional statements and Functions

In [134]:
def add_10(x):
    if x>= 100:
        x = x + 10
        return x
    else:
        print("Save More..!")

In [135]:
add_10(100)

110

In [136]:
add_10(50)

Save More..!


## working with functions having many arguments/parameters

In [139]:
# we can have arguments with a comma
def subtract_bc(a,b,c):
    result = a - b*c
    print("Value of a is: ",a)
    print("Value of b is: ",b)
    print("Value of c is: ",c)
    return result

In [140]:
subtract_bc(100,5,7)

Value of a is:  100
Value of b is:  5
Value of c is:  7


65

## Built in function in python

In [142]:
type("Bibhu")

str

In [144]:
int(5.5)

5

In [147]:
float(3)

3.0

In [148]:
str(500)

'500'

In [149]:
max(10,2,3)

10

In [150]:
min(10,2,3)

2

In [151]:
abs(-20)

20

In [153]:
list = [1,2,3,4,5]
sum(list)

15

In [157]:
round(3.66)

4

In [158]:
round(3.4455555,3)

3.446

In [159]:
2 ** 10

1024

In [160]:
pow(2,10)

1024

In [164]:
len('biswanathdehury01')

17

# 08. Python Sequences

1. Lists
2. Slicing Methods
3. Tuples
4. Dictionaries

## Lists

values in [] seperated by , ex. below

NOTE: Integers, floats, strings, all can be stored in a list

In [165]:
vehicles = ['car', 'bike', 'cycle','truck','bus','trian','plane']

In [166]:
vehicles[3]

'truck'

In [169]:
vehicles[-2]

'trian'

In [170]:
len(vehicles)

7

In [174]:
# It will repace the value in the index
vehicles[0]='Walking'

In [175]:
vehicles

['Walking', 'bike', 'cycle', 'truck', 'bus', 'trian', 'plane']

In [176]:
# Deleting a value at an index
del vehicles[0]

In [178]:
vehicles
# by this the sequence of the values also changes

['bike', 'cycle', 'truck', 'bus', 'trian', 'plane']

### Different methods used in list to modify a list

use of . "dot" followed by the function()

In [179]:
len(vehicles)

6

In [180]:
vehicles[7]='cars'

IndexError: list assignment index out of range

In [181]:
vehicles.append("Cars")

In [182]:
vehicles

['bike', 'cycle', 'truck', 'bus', 'trian', 'plane', 'Cars']

In [183]:
# adding multiple items in a list at a time: use of extend function
vehicles.extend(['audi','lambo','BMW','Ferrari','Bugati','Porsche'])

In [184]:
vehicles

['bike',
 'cycle',
 'truck',
 'bus',
 'trian',
 'plane',
 'Cars',
 'audi',
 'lambo',
 'BMW',
 'Ferrari',
 'Bugati',
 'Porsche']

## Slicing

In [186]:
vehicles[2:6]

['truck', 'bus', 'trian', 'plane']

In [187]:
# by this :2 we get the first 2 elements
vehicles[:2]

['bike', 'cycle']

In [188]:
# by this -2: we obtain the last 2 elements
vehicles[-2:]

['Bugati', 'Porsche']

In [189]:
# .Index('') method is used to find the index location of the value

vehicles.index('BMW')

9

In [192]:
# list under list

list1 = ['mama','bapa','bhai']
list2 = ['chori','lony','kau','nata']

list3=[list1,list2]
list3

[['mama', 'bapa', 'bhai'], ['chori', 'lony', 'kau', 'nata']]

In [195]:
# Sorting the list in alphabetical order

numbers=[1,2,323,4,64,9,10]
numbers.sort()
numbers

[1, 2, 4, 9, 10, 64, 323]

In [197]:
numbers.sort(reverse=True)
numbers

[323, 64, 10, 9, 4, 2, 1]

## Tuples

Tupes are placed in parenthesis () and not in brackets []

Tuples are not changeable

In [201]:
x= (10,20,30)
print(type(x))
x

<class 'tuple'>


(10, 20, 30)

In [203]:
# default it will be a tuple
y = 2,3,4
y

(2, 3, 4)

In [205]:
a,b,c = 5,10,15
c

15

In [206]:
# we can alos find tuples values based on index
x[1]

20

In [208]:
# We can put tuples inside a list
list_3 = [x,y]
list_3

[(10, 20, 30), (2, 3, 4)]

In [215]:
# tuples applications
# "28,6" - comman seperated values,
# we can print the items seperatedly

(age,years_of_experice) = "28,6".split(',')
print("Associate age is:", age)
print("Associate Years of Experice:", years_of_experice)

Associate age is: 28
Associate Years of Experice: 6


In [217]:
# Functions can return Tuple values

def rectangle_info(length,bredth):
    Area = length * bredth
    Perimeter = 2 * (length + bredth)
    return Area, Perimeter

rectangle_info(2,4)
# we can see it returned a tuple value

(8, 12)

## Dictionaries

Now we have understood about list ans tuples, it will be easy to know about disctionaries
{} - curley braces
{key-value pairs}


In [218]:
d1 = {'Stud1': 50, 'Stud2': 60, 'Stud3': 80}

In [219]:
d1

{'Stud1': 50, 'Stud2': 60, 'Stud3': 80}

In [220]:
#can access the values from its key

d1['Stud2']

60

In [221]:
# you can change the value of the perticular key

d1['Stud1']= 40

In [222]:
d1

{'Stud1': 40, 'Stud2': 60, 'Stud3': 80}

In [224]:
# we can have a list inside a dictionary

dept_employees = {'dept1':'Biswa', 'dept2':['manas', 'kau','nata']}

In [225]:
dept_employees['dept1']
# here we have only 1 employee

'Biswa'

In [226]:
dept_employees['dept2']
# in department 2 we have 3 employees

['manas', 'kau', 'nata']

In [227]:
# there is another way to fill a dictionary

team= {}
team['captain']='Dhoni'
team['vice captain']='Virat'
team['opening']='Sachin'
team['bowler']='Bhumra'

In [228]:
team

{'captain': 'Dhoni',
 'vice captain': 'Virat',
 'opening': 'Sachin',
 'bowler': 'Bhumra'}

In [230]:
print(team['captain'])

Dhoni


In [237]:
# .get method to get value for the key
print(team.get('captain'))

Dhoni


In [235]:
# if you dont have a key in dictionary, get method will not through an error, it will return 0
print(team.get('coach'))

None


# 0.9 Iterations in python

1. For loop
2. While Loop and incrementing
3. Iterations with range()
4. Combining all together


### For Loop

In [238]:
even = [0,2,4,6,8,10,12,14]

In [239]:
for n in even:
    print(n)

0
2
4
6
8
10
12
14


In [241]:
for n in even:
    print(n, end=" -> ")

0 -> 2 -> 4 -> 6 -> 8 -> 10 -> 12 -> 14 -> 

### While Loop

In [242]:
x = 0
while x <= 20:
    print(x, end=" ")
    x = x + 2

0 2 4 6 8 10 12 14 16 18 20 

In [243]:
x = 0
while x<=20:
    print(x, end=" ")
    x += 2

0 2 4 6 8 10 12 14 16 18 20 

### Create list with range() fucntion

**range(start, stop, step)** it create a sequence of integers

start = firt no. in list, default 0  
stop = last no. in the list (last value + 1)  
step = distance between consicutive integers, default 1
  

In [244]:
range(10)

range(0, 10)

In [258]:
l = [range(3,10,2)]

In [263]:
for n in range(11):
    print(  2 ** n, end = " ")

1 2 4 8 16 32 64 128 256 512 1024 

In [266]:
for x in range(20):
    if x%2==0:
        print(x, end=" ")
    else:
        print("Odd", end= " ")

0 Odd 2 Odd 4 Odd 6 Odd 8 Odd 10 Odd 12 Odd 14 Odd 16 Odd 18 Odd 

In [267]:
# another way to fetch a list

lst = [1,2,4]

for item in lst:
    print(item, end=" ")

1 2 4 

In [268]:
for item in range(len(lst)):
    print(lst[item], end=" ")

1 2 4 

**NOTE: in this style range(len(lst)), you have to use index of each item to extract**


**Problem Statement**

All conditions, 
how can we count the number of items, whose value is less than 20 in a list?


In [269]:
def count(numbers):
    total = 0
    for x in numbers:
        if x<20:
            total += 1
    return total

In [271]:
list_1 = [1,3,4,10,14,45,634,345, 12]

count(list_1)

6

**Problem Statement**

we have 2 dictionaries: Prices and Quantity, we need to find out the total sum of shopping

In [276]:
prices = {"Milk": 20,
         "Curd":40,
         "watermelon": 20}

quantity = {"Milk": 2,
            "Curd":1,
            "watermelon": 3.5}


In [277]:
total_amount = 0

for i in prices:
    total_amount += (prices[i] * quantity[i])
    
print(total_amount)

150.0


In [278]:
total_amount = 0

for i in quantity:
    total_amount += (prices[i] * quantity[i])
    
print(total_amount)

150.0


NOTE: You can see that it does not matter you loop through prices or quantity, because both have same keys. Output will remain same.

# ADVANCED PYTHON

## 1. OOPS

object = data + operator

## 2. Importing necessary modules and packages

In [282]:
import numpy as np
import pandas as pd
import matplotlib
import math
import random
import statsmodels
import pandas_datareader

## 3. Array

### Diferrence between Array and List

Array are fundamental data structure in any programming language

Array are similar to list. They represent objects. And objets in arrya are called array elements.

**Main difference between Array and list is,** 

All the elements in the Array must be the same data type. Ex, Either all floats, or all integers

But in a list, it can contain values of different datatypes.



In [283]:
# Array is in numpy module

# here we will place a list of list within ()
a= np.array([[2,3,4],[6,7,8]])
a

array([[2, 3, 4],
       [6, 7, 8]])

**Numpy n-dimentional array = ndarray**


NOTES:

1. An ndarray is always homogeneous. Means it contrains only similar datatype

2. You can see there will be error message dtype, if we have different data type or mismatch dimentions inside array

In [284]:
b= np.array([[2,"ram",4],[6,7,8]])
b

array([['2', 'ram', '4'],
       ['6', '7', '8']], dtype='<U11')

In [285]:
c= np.array([[2,4],[6,7,8]])
c

array([list([2, 4]), list([6, 7, 8])], dtype=object)

In [288]:
a.shape

# we can see the shape of array, 2 rows and 3 columns

(2, 3)

We can find the element in array and also modify the same.

In [291]:
arr1 = np.array([[0,1,2,3], [4,5,6,7]])
arr1.shape

(2, 4)

In [292]:
# finding the element in array, by row,column 
arr1[1,3]

7

In [293]:
# by this we can assign new value to array
arr1[0,3]=999

In [294]:
arr1

array([[  0,   1,   2, 999],
       [  4,   5,   6,   7]])

In [296]:
# this will extract 0th row for us
arr1[0]

array([  0,   1,   2, 999])

## 4. What is the importance of Array?, why numpy array!

1. Because arrays are basic and imp building block of any data structure.

2. It will carry and organize values into Vectors, matrices, and other multidimential objects.

**mathmatical importance**

**1D-Array also called Vector**   

A Vector has both magnitude and direction. x axis and y axis (3,5). This is a one dimentional vector.

**2D-Array also called Matrix** 

Most financial calculations are heavly use Matrices for analysis. Heavy operations can be applied. 
Matrix (Additions, sub, mul, div, transposing.....)

In [298]:
OneD_arr = np.array([3,5])
OneD_arr

array([3, 5])

## 5. Generating Random Numbers

In [299]:
import random

In [301]:
prob = random.random()
print(prob)

# as we know probalbilit lies between 0 and 1

0.8356852679546194


In [303]:
#randint() is used to generate a random integer between 2 numbers.

number = random.randint(1,10)
number

8

In [304]:
import numpy as np

In [306]:
# lets create a matrix with numbers between 0 to 9 and matrix size of 4*6

np.random.randint(0,9,(4,6))

array([[2, 0, 4, 7, 8, 6],
       [5, 6, 2, 2, 7, 2],
       [0, 8, 1, 8, 8, 3],
       [2, 3, 5, 8, 0, 6]])

This is very powerful technique that we will be using in Monte Carlo technique, one of the most imp financial tool in analysis in the whole world

In [311]:
np.random.randint(10,20,(4,4))
# 4*4 matrix

array([[18, 10, 11, 13],
       [10, 13, 10, 18],
       [12, 10, 19, 11],
       [18, 15, 17, 11]])